kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_AUTH_TYPE: approle
  # TODO: get both values from vault, See: Create App Role section in README
  AVP_ROLE_ID: 
  AVP_SECRET_ID: 
  AVP_TYPE: vault
  VAULT_ADDR: http://vault.default.svc:8200
